name: CI

on: [push]

jobs:
  flatpak:
    name: "Flatpak Build"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:8
      options: --privileged
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: Alohomora.flatpak
        manifest-path: io.github.z0o0p.alohomora.yml
        run-tests: true
        repository-name: appcenter
        repository-url: https://flatpak.elementary.io/repo.flatpakrepo
        cache-key: "flatpak-builder-${{ github.sha }}"
