name: CI

on: [push]

jobs:
  flatpak:
    name: "Flatpak Build"
    container:
      image: ghcr.io/elementary/flatpak-platform/runtime:8
      options: --privileged
    strategy:
      matrix:
        variant:
        - arch: x86_64
          runner: ubuntu-24.04
        - arch: aarch64
          runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.variant.runner }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build (${{ matrix.variant.arch }})
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: Alohomora.flatpak
        manifest-path: io.github.z0o0p.alohomora.yml
        run-tests: true
        repository-name: appcenter
        repository-url: https://flatpak.elementary.io/repo.flatpakrepo
        cache-key: flatpak-builder-${{ matrix.variant.arch }}-${{ github.sha }}
        arch: ${{ matrix.variant.arch }}
